services:
  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_volume:
