-- Create "todos" table
CREATE TABLE "todos" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "title" character varying NOT NULL,
  "description" character varying NULL,
  "status" character varying NOT NULL,
  PRIMARY KEY ("id")
);
